### PR TITLE
Swift 4.1

### PR DESCRIPTION
**Pull request by ilyapuchka**

### CODE REVIEW

**Comment by hartbit** [comment]
Is there anything I can do to help get a Swift 4.1 compatible version through?

**Comment by kdawgwilk** [comment]
I am also wondering the same thing.  I am feeling kind of helpless at this point and am considering dropping sourcery as a dependency 😞

**Comment by krzysztofzablocki** [comment]
@hartbit @kdawgwilk you'd need to coordinate with @ilyapuchka but there are some build failures still left for this branch to be mergable

**Comment by hartbit** [comment]
@krzysztofzablocki the build failures seem to be only related to the fact that CircleCI is still building it with Xcode 9.2, whereas it needs to be configured with Xcode 9.3

**Comment by krzysztofzablocki** [comment]
@ilyapuchka is there anything else we need to merge this?

**Comment by ilyapuchka** [comment]
We need to look closer into this https://github.com/krzysztofzablocki/Sourcery/issues/568#issuecomment-378083284

**Comment by kdawgwilk** [comment]
wtf...why isn't CI running?

**Comment by ilyapuchka** [comment]
@kdawgwilk circleci unfortunately does not support Xcode 9.2 yet, so it's not even running builds.

"You specified an unsupported Xcode version"

**Comment by kdawgwilk** [comment]
It actually does I jsut found out today but it needs to be `9.3.0` instead of `9.3` for some dumb reason

**Comment by kdawgwilk** [comment]
New PR #585 to fix that version for ci.  For reference https://discuss.circleci.com/t/xcode-9-3-beta-4-release-for-circleci-2-0/20757

**Comment by ilyapuchka** [comment]
@kdawgwilk it still fails with the same error...

**Comment by hartbit** [comment]
@ilyapuchka where do you see the error?

**Comment by hartbit** [comment]
@kdawgwilk btw, this is the CircleCI Xcode 9.3 beta 4 release. I don't think that's a good idea.

**Comment by ilyapuchka** [comment]
https://circleci.com/gh/krzysztofzablocki/Sourcery/tree/swift4_1

screen shot 2018-04-05 at 13 48 09
screen shot 2018-04-05 at 13 48 19

**Comment by ilyapuchka** [comment]
I don't think they already support it, the last announcement is about beta 4

**Comment by ilyapuchka** [comment]
Seems like we need to migrate to CircleCI 2.0.....

**Comment by kdawgwilk** [comment]
I think its the beta 4 for now until they get the 9.3 GM image read to go

**Comment by ZevEisenberg** [comment]
It looks like the 9.3 GM is already running on Circle 2.0: https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-405/index.html

via https://circleci.com/docs/2.0/testing-ios/

**Comment by chrisballinger** [comment]
I can verify CircleCI 2.0 is running Xcode 9.3 GM 9E145. See "Check Xcode Version" in https://circleci.com/gh/Raizlabs/ios-template/151 

```
#!/bin/bash --login -o pipefail
xcodebuild -version
Xcode 9.3
Build version 9E145
```

**Comment by ZevEisenberg** [comment]
We just got CircleCI working on a couple of projects. It's not trivial, but maybe [this working config](https://github.com/Raizlabs/BonMot/pull/323) will help - it may be a little more readable than the comprehensive documentation. I can also help debug 2.0 stuff, since I just went through the migration.

**Comment by ilyapuchka** [comment]
your help to make it work will be welocme

**Comment by ZevEisenberg** [comment]
WIP PR into this branch is [here](https://github.com/krzysztofzablocki/Sourcery/pull/587). Could use some help with build failures, if anyone has time/ideas.

**Comment by Liquidsoul** [comment]
I tried to rebase this on `master` and the build failed. I am investigating this right now.

**Comment by ilyapuchka** [comment]
@Liquidsoul please don't make a release yet. There are fixes on master that I'd like to release to have them for Swift 4. Then we should update this branch and make release for Swift 4.1 with the same functionality.

**Comment by ilyapuchka** [comment]
And I'm still not convinced everything works fine with Swift 4.1, I was seeking some `Bus error`'s

**Comment by Liquidsoul** [comment]
I am putting the `hold` tag on this then. We'll remove it once we are confident enough to merge this.
@ilyapuchka Do you want me to make a release `0.12.0` with what is currently in `master`?

**Comment by ilyapuchka** [comment]
@Liquidsoul If you have time. I think 0.11.1 should be fine, it only fixes one issue and updates sourcekitten to latest version

**Comment by chrisballinger** [comment]
Can you make a "0.12.0-beta" release tag with the 4.1 changes?

**Comment by chrisballinger** [comment]
Since the CocoaPods version just downloads a precompiled binary blob release, it's not as easy to test the changes in the 4.1 branch. https://github.com/krzysztofzablocki/Sourcery/blob/190d1cb2b46ecc68c36f35d2aa3d2699df89a3e4/Sourcery.podspec#L18

**Comment by ilyapuchka** [comment]
You can checkout the project and run it from Xcode pointing to your sources if you want to check how it behaves on your code base.

**Comment by Liquidsoul** [comment]
@ilyapuchka I've just published the `0.11.1` on GitHub and made a PR for homebrew.
However, I am not listed as an owner of the pod to do the cocoapods release 😞 
Could you please make the cocoapods release or add me as an owner of the pod?

**Comment by ilyapuchka** [comment]
I think @krzysztofzablocki can add you, I don't think anyone else have access

**Comment by krzysztofzablocki** [comment]
@Liquidsoul I'll need an email you used for trunk

**Comment by ilyapuchka** [comment]
@Liquidsoul if you didn't do that I can do it now

**Comment by Liquidsoul** [comment]
@krzysztofzablocki I used the same email I use for my commits here for `pod trunk` (liquidsoul[at]liquidsoul.fr)
@ilyapuchka I will not be able to do that until tomorrow once I have access, it would be nice if you could do that :)

**Comment by ilyapuchka** [comment]
@Liquidsoul I think we actually need to re-release 0.11.1 because it seems like we use different versions of some dependencies for binaries distributed via CocoaPods and SPM/Homebrew

**Comment by Liquidsoul** [comment]
@ilyapuchka Just saw that SPM dependencies versions do not match the ones in cocoapods 🤔 
The released packaged app in GitHub is correct, it's the source version built using SPM that's not.
So maybe I need to withdraw the [Homebrew update](https://github.com/Homebrew/homebrew-core/pull/26350). But fixing this `0.11.1` homebrew release seems to me like a PITA 😓 
Maybe we should just let the `0.11.1` as-is, fix the SPM versions and release a `0.11.2` with this fix?
I can do this other release tomorrow morning.
What do you think @krzysztofzablocki ?

**Comment by ilyapuchka** [comment]
0.11.2 should be fine I think. I'm currently trying to make those versions in sync and it's all such a mess...

**Comment by Liquidsoul** [comment]
Yeah... I think we have _some_ work to do on that and the release process/scripts 😅

**Comment by krzysztofzablocki** [comment]
agreed about it being a bit of a mess, I'm with @ilyapuchka on versioning

**Pull request merged**
