### PR TITLE
Fix running sourcery script

### PR DESCRIPTION
**Pull request by serejahh**
Hey. I tried to run the sample app, but I got some errors. It seems the CLI tool has been changed, but the example app hasn't. Now everything is OK

### CODE REVIEW

**Comment by ilyapuchka** [comment]
👍 thanks!

**Comment by Antondomashnev** [comment]
@serejahh thanks for the fix, we're happy to merge your PR, but could you please update CHANGELOG first.

**Comment by serejahh** [comment]
Done 😃

**Comment by serejahh** [comment]
Thank you guys for the awesome lib 👍

**Pull request merged**
