### PR TITLE
Speed up compile of autohashable

### PR DESCRIPTION
**Pull request by Lutzifer**

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
@Lutzifer awesome work, mind solving the conflict that appeared after I merged your other pr?

**Comment by Lutzifer** [comment]
solved

**Comment by ilyapuchka** [comment]
Should this also update templates test project?

**Comment by krzysztofzablocki** [comment]
yeah I think so

**Comment by Lutzifer** [comment]
ah, didn't run the tests for this one actually 🤭

**Comment by Lutzifer** [comment]
@krzysztofzablocki I will think about joining

**Comment by krzysztofzablocki** [comment]
@Lutzifer any updates on the templates here?

**Comment by krzysztofzablocki** [comment]
@Lutzifer might updating the template tests or should we?

**Comment by Lutzifer** [comment]
sorry, I still did not find the time for this, so feel free to continue

**Pull request merged**
