### PR TITLE
Add support for parsing documentation comments on declarations

### PR DESCRIPTION
**Pull request by cobbal**
As mentioned in  #766

### CODE REVIEW

**Comment by cobbal** [comment]
@krzysztofzablocki Any update on this?

**Comment by cobbal** [comment]
> I'll get on this soon, started new job last week so been quite busy

Congrats! I understand that. It's not a rush, but I just wanted to make sure it was moving along :) And thank you for all you do for this project :)

**Review by krzysztofzablocki — APPROVED** [review]

**Comment by mhdhejazi** [comment]
Thank you @cobbal and @krzysztofzablocki for this great feature!

I'm not able to get Sourcery to parse documentation unless I pass `--disableCache`. I just wanted to confirm that this is the expected behaviour.

Also, it'd be great if Sourcery docs are also updated to mention the new `documentation` property.

**Comment by krzysztofzablocki** [comment]
@mhdhejazi have you tried nuking old cache manually? try removing the cache and then it will re-create it on next run, let me know if you are still running into issue without `disableCache` after doing so

**Pull request merged**
