### PR TITLE
Update for Swift 4

### PR DESCRIPTION
**Pull request by zats**
Let me know if you want this to be one commit - I think now it can be handled during merge?

I see few fantom test failures that don't show up in the console, wanted to kickoff CI tests

### CODE REVIEW

**Comment by zats** [comment]
I'm not sure if the failure has to do with my code changes or with move to Xcode 9.
I can't seem to trigger the build to run again to see if it's a flaky failure or something consistent
Any ideas?

**Comment by ilyapuchka** [comment]
Hi @zats . Thanks for the contribution. But it does not seem that you actually migrated Sourcery to Swift 4, it's built with Swift 3.2. Is this intentional?

**Comment by ilyapuchka** [comment]
I also don't see any failing tests, the failure on CI is, I guess, related to code coverage service

**Comment by zats** [comment]
hmm, it started to fail the build on master, is that expected?

**Comment by ilyapuchka** [comment]
of course, we need to fix code coverage integration, I guess it does not work properly with Xcode 9 or something

**Comment by zats** [comment]
gotcha, thanks for taking the time to look into it ❤️

**Pull request merged**
