### PR TITLE
[WIP] Incorrect insert position of `inline:auto` code

### PR DESCRIPTION
**Pull request by Liquidsoul**
This PR contains a failing test for issue #320

### CODE REVIEW

**Comment by Antondomashnev** [comment]
@Liquidsoul I'm a bit confused with the result of the CI 😄

**Comment by Liquidsoul** [comment]
Success with a failing test, nice! 🤣

**Comment by Antondomashnev** [comment]
@Liquidsoul let me check it locally on my machine 😄

**Comment by Antondomashnev** [comment]
Hm, and CI in the web interface shows an error:

**Comment by ilyapuchka** [comment]
@Liquidsoul @Antondomashnev #323 should resolve this issue

**Pull request closed without merging**
