### PR TITLE
Release to homebrew rake task;

### PR DESCRIPTION
**Pull request by Antondomashnev**
This PR addresses the #15. As far as I understood the last sub-task of the issue is to actually automate the process of releasing a formula update.
I've used some code that @orta [mention](https://github.com/CocoaPods/CocoaPods-app/blob/master/Rakefile#L1217-L1259) and also the tasks from [SwiftGen](https://github.com/SwiftGen/SwiftGen/blob/b145166708063197ce1ff4934fe65e3fb70a030b/Rakefile#L266).

I'm not sure how to test it properly, but what I've done - is to test a PR into my [fork](https://github.com/Antondomashnev/homebrew-core/pulls) from fork of Sourcery.

The PR is marked as [WIP] because I'm not sure the work is done as we may require better testing and also we will require to update `RELEASING.md` with some new information.

### CODE REVIEW

**Comment by Antondomashnev** [comment]
Now WIP anymore 😄

**Comment by ilyapuchka** [comment]
@Antondomashnev did you try it during 0.8 release?

**Comment by Antondomashnev** [comment]
Nope, was not using it, I wanted to have reviewed it first.

**Comment by ilyapuchka** [comment]
I have no idea to be honest what it takes to publish in homebrew, so I think jut trying it out will be the best review for it.

**Comment by Antondomashnev** [comment]
Hah @ilovezfs was faster. `0.8.0` has been already released. Will wait to try out the script for the next release 😄

**Comment by Liquidsoul** [comment]
@Antondomashnev Did you try this out to publish the `0.9.0` to homebrew?

**Comment by Antondomashnev** [comment]
@Liquidsoul I've tried but as I've been using a new laptop it wasn't successful. But I'll finalize it soon.

**Comment by Antondomashnev** [comment]
@ilovezfs could you please wait for the next release to homebrew? We need to try out our script but I'm always late as you already uploaded it.

**Comment by Antondomashnev** [comment]
Although I'm still not able to test it I vote to merge it in and test next release, we can do even 0.9.1 release otherwise I feel we will skip this merge for a while.

@ilyapuchka @Liquidsoul @krzysztofzablocki ?

**Comment by ilovezfs** [comment]
@Antondomashnev just mark it prerelease when you want me to keep away :)

**Comment by Liquidsoul** [comment]
I think we should integrate this and use it/debug it the next time we will release a version.

**Comment by Antondomashnev** [comment]
I will keep the related issue open until we finally try the script.

**Pull request merged**
