### PR TITLE
Update dependencies to fix build on Xcode 13 and support Swift 5.5

### PR DESCRIPTION
**Pull request by 4brunu**
This tries to fix https://github.com/krzysztofzablocki/Sourcery/issues/989 and add support for Swift 5.5.

I think that I also need to update `lib_InternalSwiftSyntaxParser.dylib` but I don't know how.

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
@4brunu thanks🙇   can you copy `lib_InternalSwiftSyntaxParser.dylib` from Xcode 13 folder? it should be in `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx`

**Comment by 4brunu** [comment]
Thanks for the guidance, it's done.
I'm not sure if something is still missing or if it's now complete

**Comment by 4brunu** [comment]
I found another issue with the `XcodeProj` that doesn't build with the Xcode 13, I'm also upgrading it now.

**Comment by 4brunu** [comment]
@krzysztofzablocki after upgrading the dependency `XcodeProj` it now builds in the SPM project.
But I'm not sure why the CI is failing.
Any tip on this?

**Comment by 4brunu** [comment]
I tried to run locally `bundle exec rake validate_docs`, since it's the command that is failing on CI, and it passes locally.

**Comment by krzysztofzablocki** [comment]
I'll figure it out, I want to spend some time on sunday to get pr's in and make a new release

**Comment by 4brunu** [comment]
Thanks 👍

**Comment by Cyberbeni** [comment]
Since PathKit had to be updated due to a breaking change, it also breaks compatibility the other way too. You have to update the circleci config to use Xcode 13: https://github.com/krzysztofzablocki/Sourcery/blob/2ed1c1bc64cac435272e09ff14d09cb6faeaa27f/.circleci/config.yml#L6

**Comment by 4brunu** [comment]
Thanks for the tip, I have updated it, let's see if CI now passes 👍

**Comment by 4brunu** [comment]
Thanks for the tip, I have updated it, let's see if CI now passes 👍

**Comment by 4brunu** [comment]
That did help and we have some progress, but now it shows the error:
```
#!/bin/bash --login -eo pipefail
bundle exec rake tests
tput: No value for $TERM and no -T specified

== Running Unit Tests ==

set -o pipefail && xcodebuild -scheme sourcery | xcpretty -c
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:564DBC60-8304-2C30-DE75-FB010DB1F0F8 }
{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:564DBC60-8304-2C30-DE75-FB010DB1F0F8 }
{ platform:macOS, name:Any Mac }
{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
xcodebuild: error: Building a Swift package requires that a destination is provided using the "-destination" option. The "-showdestinations" option can be used to list the available destinations.
rake aborted!
Command failed with status (70): [set -o pipefail && xcodebuild -scheme sour...]
```

**Comment by krzysztofzablocki** [comment]
brought in #992, thanks for this @4brunu, I'll need to figure out some swift template stuff and add 2 features I wanted but should be doing release soon

**Pull request closed without merging**
