### PR TITLE
Migrate to Swift 4, SwiftPM 4 and Xcode 9.2

### PR DESCRIPTION
**Pull request by hartbit**
In preparation for a future Pull Request, I migrated Sourcery to Swift 4, I migrated the SwiftPM Package.swift manifest to the version 4, and I got everything working and building in Xcode 9.2

### CODE REVIEW

**Comment by hartbit** [comment]
@krzysztofzablocki The Circle-CI failure seems unrelated.

**Comment by hartbit** [comment]
I pushed a new version of the PR based off my previous #490 PR.

**Comment by krzysztofzablocki** [comment]
@ilyapuchka @Antondomashnev do we want to make a release with previous Swift version and current master changes before we merge this?

**Comment by Antondomashnev** [comment]
@krzysztofzablocki I haven't really worked with swift much last 4 months, so I'm not sure about the usage of different versions across the community. I'd say maybe we can carry on with the only new version of swift and mention these in the release changelog.

**Comment by ilyapuchka** [comment]
I think it's ok to merge

**Comment by AndrewSB** [comment]
Mentioning which version of Swift/XCode was used to compile each release would be really useful! I wouldn't have to dig around in Pull Requests to figure out why sourcery isn't working 😄

**Comment by krzysztofzablocki** [comment]
@AndrewSB fair point, will try to do that 👍

**Pull request merged**
