### PR TITLE
Use modifiers to determine `isFinal`

### PR DESCRIPTION
**Pull request by robertjpayne**
isFinal is no longer part of the parsed attributes but is instead classified as a modifier.

This fixes that.

I can't find good information on the repository about steps to take to write a test that is functional or how to update other documentation required. If you can provide any information about how to write a test for the project or other documentation that needs to be updated happy to help.

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
hey @robertjpayne, thanks for contributing but I think we need to update other isFinal extensions e.g. https://github.com/krzysztofzablocki/Sourcery/blob/4282b785b32f8a2bbc77d39277785cbe27d91daf/SourceryRuntime/Sources/AST/Subscript.swift (just search for `isFinal` in repo to find other places).

As for tests they probably should go into this file https://github.com/krzysztofzablocki/Sourcery/blob/master/SourceryTests/Parsing/FileParser%20%2B%20AttributesModifierSpec.swift#L85 you can just follow the setup there and just use `isFinal` accessor for all those instances

**Comment by krzysztofzablocki** [comment]
@robertjpayne I'll grab your changes and just do it since I want to cut a new release after the wekeend, thanks for help :)

**Comment by robertjpayne** [comment]
@krzysztofzablocki thanks! Sorry I ran out of time this last week and didn't have time to look at any of this 😞

**Comment by krzysztofzablocki** [comment]
@robertjpayne no worries

**Pull request closed without merging**
