### PR TITLE
Added generic requirements and generic parameters to Subscript

### PR DESCRIPTION
**Pull request by leonspok**
We found that there is no enough information in the current version of `Subscript`. Following the recommendation from #996, I added:

* New type `GenericParameter` to describe the contents of generic parameters clause in subscript definition
* Fields `genericParameters`, `genericRequirements` and `isGeneric` to Subscript model.

Now this example:

```
protocol Subscript: AnyObject {
    subscript(arg1: Int) -> Int? { get set }
    subscript<T: Hashable & Cancellable>(arg1: String) -> T? { get set }
    subscript<T>(with arg1: String) -> T? where T: Cancellable { get }
}
```

Produces output (protocol part is removed):

```
Subscript: parameters = [MethodParameter: argumentLabel = Optional("arg1"), name = arg1, typeName = Int, `inout` = false, isVariadic = false, typeAttributes = [:], defaultValue = nil, annotations = [:], asSource = arg1: Int], returnTypeName = Int?, actualReturnTypeName = Int?, isFinal = false, readAccess = internal, writeAccess = internal, isMutable = true, annotations = [:], documentation = [], definedInTypeName = Optional(Subscript), actualDefinedInTypeName = Optional(Subscript), genericParameters = [], genericRequirements = [], isGeneric = false, attributes = [:], modifiers = []

Subscript: parameters = [MethodParameter: argumentLabel = Optional("arg1"), name = arg1, typeName = String, `inout` = false, isVariadic = false, typeAttributes = [:], defaultValue = nil, annotations = [:], asSource = arg1: String], returnTypeName = T?, actualReturnTypeName = T?, isFinal = false, readAccess = internal, writeAccess = internal, isMutable = true, annotations = [:], documentation = [], definedInTypeName = Optional(Subscript), actualDefinedInTypeName = Optional(Subscript), genericParameters = [GenericParameter: name = T, inheritedTypeName = Optional(Hashable & Cancellable)], genericRequirements = [], isGeneric = true, attributes = [:], modifiers = []

Subscript: parameters = [MethodParameter: argumentLabel = Optional("with"), name = arg1, typeName = String, `inout` = false, isVariadic = false, typeAttributes = [:], defaultValue = nil, annotations = [:], asSource = with arg1: String], returnTypeName = T?, actualReturnTypeName = T?, isFinal = false, readAccess = internal, writeAccess = , isMutable = false, annotations = [:], documentation = [], definedInTypeName = Optional(Subscript), actualDefinedInTypeName = Optional(Subscript), genericParameters = [GenericParameter: name = T, inheritedTypeName = nil], genericRequirements = [GenericRequirement: leftType = AssociatedType: name = T, typeName = nil, rightType = GenericTypeParameter: typeName = Cancellable, relationship = conformsTo, relationshipSyntax = :], isGeneric = true, attributes = [:], modifiers = []
```

### CODE REVIEW

**Comment by art-divin** [comment]
👋🏻  Hello @leonspok ,

such a wonderful contribution right before the 2.1.3 release, thank you very much!
Although this PR does not include support for Stencil for the new `GenericParameter`, it is negotiable since Linux support is experimental. So I have added a note in this regard here: #1198.

### Context

In order to enable the dynamic member lookup in `GenericParameter`, we need to add DynamicMemberLookup protocol conformance for Linux-only version of `GenericParameter.swift` file - like it is done for most of other types in Sourcery at the moment. As of now, automatically generated code does not support such generation for dynamic member lookup on non-Darwin systems.

**Comment by art-divin** [comment]
It would be amazing though if you could edit CHANGELOG.md file to mention this contribution for the release notes.

**Comment by leonspok** [comment]
Thanks @art-divin! I had a feeling this would require a bit more changes than I did :)
Sure, I'll have a look at #1198 and add everything what's missing.
Plus CHANGELOG.md

**Comment by art-divin** [comment]
Thank you, if needed, it is a matter of adding the same file again, hidden behind an '#if', and implementing the 'DynamicMemberLookup' protocol conformance only for non-Darwin platforms.

You could also add a test by adjusting 'AutoMockable.stencil' file and doing something with the new type there, then adding code for testing in 'AutoMockable.expected' and 'AutoMockable.swift'.

But, as you can see, it involves multiple domains of knowledge, so feel free to just adjust Changelog file for this PR. 🤝

**Comment by leonspok** [comment]
@art-divin I'm a bit puzzled by this issue (I get it while running tests with `rake tests`):

```
Test Suite 'TemplatesTests' started at 2023-12-21 17:48:41.050.
2023-12-21 17:48:41.211 sourcery[16037:22956534] -[SourceryRuntime.GenericParameter encodeWithCoder:]: unrecognized selector sent to instance 0x600000861ca0
Error Domain=NSCocoaErrorDomain Code=4866 "Caught exception during archival: -[SourceryRuntime.GenericParameter encodeWithCoder:]: unrecognized selector sent to instance 0x600000861ca0
```

I don't see the difference between Codable support in `GenericRequirement` and the newly added `GenericParameter`.

**Comment by art-divin** [comment]
@leonspok I am running tests, cloned your fork. 

Best puzzles.

**Comment by art-divin** [comment]
@leonspok the issue is that there are files which are injected at Runtime of Sourcery into the generated project, which is then compiled to verify that the generated code is compilable Swift code, and these files need to include the new types. In fact, they need to include all types which can be used in templates.

So, after adding a new types to `SourceryRuntime` you need to add these files manually to:

1. `SourceryRuntime.content.generated.swift` file
2. `SourceryRuntime_Linux.content.generated.swift` file

## Context

Before, Sourcery did support generating code "for itself" into file named `SourceryRuntime.content.generated.swift` by executing sourcery from its own root folder in this repository. But after Linux support integration, the generated code cannot be automatically added to the mentioned file because of:

1. files are now split per platform due to the missing KVC in Foundation / on non-Darwin platforms
2. extensions for Equality are now inside of class definitions for all classes used by Sourcery and by SourceryRuntime

**Comment by art-divin** [comment]
Here's a patch you can apply which fixes the failing tests.

[Sourcery-leonspok-c6d93f3-added missing NSCoding facilities.patch](https://github.com/krzysztofzablocki/Sourcery/files/13746289/Sourcery-leonspok-c6d93f3-added.missing.NSCoding.facilities.patch)

**Comment by leonspok** [comment]
@art-divin Thank you for the patch! I made the macOS checks passing, but tests on Ubuntu are still failing for different reasons and I'm not even sure if this is caused by my changes.

I also added some logic to AutoMockable template to test the new properties of `Subscript`. Though I didn't implement the actual mocking. This looks like a substantial change worth of a separate PR. But at least the generated code should be compilable, so other users of Sourcery relying on AutoMockable template can continue using it. 

CHANGELOG.md is also updated.

I would appreciate if you had a look at the Linux tests. If these failures are caused by my changes, then I'll return to this PR once I'm back from holidays (2nd of January). 

Thanks!

**Comment by art-divin** [comment]
👋🏻  Hey @leonspok ,

Thank you very much for your work!  🤝 

> I would appreciate if you had a look at the Linux tests. If these failures are caused by my changes, then I'll return to this PR once I'm back from holidays (2nd of January).

I'll debug and report what is the reason and how to resolve it.
I wish you am amazing, joyful holiday season 🎉

**Comment by leonspok** [comment]
Hi @art-divin! I hope you had a great holiday week! 

I'm back to work and I'll continue investigating the issue with linux tests. If you have any clues, this would be very helpful :)

**Comment by leonspok** [comment]
🎉 All tests passed!

**Comment by art-divin** [comment]
Hey @leonspok ,

thank you for resilience and eagerness to work with kind_of a messy state regarding the Linux support.

Looking forward to our next collab 🙌🏻👏🤝

**Pull request merged**
