### PR TITLE
Fixes Uppercase Sources link for SwiftPM

### PR DESCRIPTION
**Pull request by vknabel**

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
This works, Danger is drunk, I'm merging 👍

**Comment by mbarclay** [comment]
HI @vknabel I can see you're working on this now :) I am trying to import using SPM using...and getting the following error.
```import PackageDescription
let package = Package(
    name: "sandpit",
    dependencies: [
        .Package(url: "https://github.com/Alamofire/Alamofire.git", majorVersion: 4, minor: 2),
        .Package(url: "https://github.com/krzysztofzablocki/Sourcery.git", majorVersion: 0)
    ]
)

warning: refname '0.4.4' is ambiguous.
warning: refname '0.4.4' is ambiguous.
HEAD is now at a2018a3 docs: increase version metadata to 0.4.4
Resolved version: 0.4.4
error: The package at `/Users/malcolm-barclay/Desktop/Sandpit/Packages/Sourcery.git' has no Package.swift for the specific version: 0.4.4```

**Comment by krzysztofzablocki** [comment]
@mbarclay you'll need to grab it in few minutes, I need to release new version afaik, releasing 0.4.5 now and that should work with swift PM

**Comment by krzysztofzablocki** [comment]
@mbarclay try now and let me know if it works

**Comment by mbarclay** [comment]
@krzysztofzablocki OK I can see the new 0.4.5 tag in git, but for some reason SPM is not, found tags...

```error: The dependency graph could not be satisfied. The package (https://github.com/krzysztofzablocki/Sourcery.git) with version tag in range (0.5.0..<0.5.9223372036854775807) is not found. Found tags ([0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4])```

**Comment by mbarclay** [comment]
My Package.swift file:
```import PackageDescription

let package = Package(
    name: "sandpit",
    dependencies: [
        .Package(url: "https://github.com/Alamofire/Alamofire.git", majorVersion: 4, minor: 2),
        .Package(url: "https://github.com/krzysztofzablocki/Sourcery.git", majorVersion: 0, minor: 4)
    ]
)```

**Comment by krzysztofzablocki** [comment]
did you remove cache?

**Comment by mbarclay** [comment]
I tried a `swift build --clean` I am missing something here? Sorry I am new to the ways of SPM :]

**Comment by vknabel** [comment]
`swift build --clean` just cleans `.build/` as far as I know. `swift package update` fetches all tags again.

**Pull request merged**
