### PR TITLE
fix ReceivedInvocations's type

### PR DESCRIPTION
**Pull request by Cookiezby**
Recently I am using Sourcery to refactoring my project, it is awesome project!  I also use the AutoMockable to help me generate the mock class for unit test. Then I find a tiny problem.

```swift
//sourcery:AutoMockable
protocol Test {
    func send(message: String?)
}
```
the generated code is
```swift
class TestMock: Test {
    //MARK: - send

    var sendMessageCallsCount = 0
    var sendMessageCalled: Bool {
        return sendMessageCallsCount > 0
    }
    var sendMessageReceivedMessage: String?
    var sendMessageReceivedInvocations: [String] = []
    var sendMessageClosure: ((String?) -> Void)?

    func send(message: String?) {
        sendMessageCallsCount += 1
        sendMessageReceivedMessage = message
        sendMessageReceivedInvocations.append(message) // this will cause compile error
        sendMessageClosure?(message)
    }
}
```
So I edit the AutoMockable.stencil, and It works, hope my solution is the right way.

### CODE REVIEW

**Comment by Cookiezby** [comment]
I found use typeName directly will have some problem with the closure, so I check the type, if it is optional, add a "?" at the end of the type.

**Comment by krzysztofzablocki** [comment]
hey @Cookiezby, thanks for contributing, could you add the case this fixes to TemplateTests projects and update the expected files to verify that this works correctly?

**Comment by Cookiezby** [comment]
Hi @krzysztofzablocki , thank for your response, I will check it.

**Comment by Cookiezby** [comment]
@krzysztofzablocki  Hi, I check the template project, and found the AutoMockable.expected is little different according to the AutoMockable.stencil. The name of the parameter name XXXInvacations seem to be XXXReceivedInvacations, so I fix the name in expected file.

**Comment by ilyapuchka** [comment]
Thanks @Cookiezby !

**Pull request merged**
