### PR TITLE
Fixed typo in README

### PR DESCRIPTION
**Pull request by jschmid**

### CODE REVIEW

**Comment by ilyapuchka** [comment]
Good catch =) Can you also fix that in guides doc and run jazzy, so that this fix make it to the docs too?

**Comment by jschmid** [comment]
@ilyapuchka I updated the docs, but running `jazzy` updates a few other files too, so I don't know if I should commit them.

**Comment by ilyapuchka** [comment]
For now commit everything that is changed after running `jazzy --clean`. That's what I do. We can figure out if we should ignore it or not later.

**Comment by jschmid** [comment]
Alright done 👍

**Pull request merged**
