### PR TITLE
Camel case / Snake case filters

### PR DESCRIPTION
**Pull request by bolismauro**
This PR adds two new filters to convert a camel case string to a snake case one and vice versa

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
Hey thanks for contributing :) 
We are going to integrate https://github.com/SwiftGen/StencilSwiftKit in upcoming release so worth checking if they don't already handle it, I can take a look when I finish some refactoring tweaks

**Comment by bolismauro** [comment]
Alright :)
Do you have an eta per the next release?

**Comment by krzysztofzablocki** [comment]
I should do it this week, probably weekend

**Comment by krzysztofzablocki** [comment]
@bolismauro I think this is covered by https://github.com/SwiftGen/StencilSwiftKit, or if not lets add it there instead of here, next release after that will contain it

**Comment by bolismauro** [comment]
They miss the camel case to snake (according to the documentation).
I'll send a PR

**Pull request closed without merging**
