### PR TITLE
Checking for processed ranges instead of replacing content with spaces when processing typealiases

### LINKED ISSUE #65: Figure out more reliable approach to parsing typealiases
I've created a workaround for the crash we were having parsing the typealiases, [take a look here](https://github.com/krzysztofzablocki/Sourcery/commit/9e2f8f548a5d467eeff75a0e1ad29a17e100613a). 

I'm still not sure that this is reliable approach so if we can find something that doesn't rely on modifying the string contents, that should be a better way of doing it.

### PR DESCRIPTION
**Pull request by ilyapuchka**
Resolves #65

I guess it should be much more reliable now, at least no need for weird operations with strings.

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
I run it against NYT codebase and the performance is significantly affected: 
current master takes: `8s`
this version takes: `77s`

you can see performance by just adding this in main:
```swift
let time = CACurrentMediaTime()
defer { print("Time: \(CACurrentMediaTime() - time)") }
```

Maybe we should leave current implementation as is for now? we can come back to this if we get crash reports from people

**Comment by ilyapuchka** [comment]
@krzysztofzablocki I'll try to see how that can be improved

**Comment by ilyapuchka** [comment]
@krzysztofzablocki I've made some changes, can you please try again?
P.S. we surely need to implement a set of performance tests

**Comment by krzysztofzablocki** [comment]
Time: 36.8333016719989

It's better but still way slower than your initial approach with my tweak, shall we close this for now? If we encounter crashes or wrong functionality we can go back to this, but no point in wasting our time if it works properly now

**Comment by ilyapuchka** [comment]
Sure, I'll close it

**Comment by krzysztofzablocki** [comment]
your initial idea was the best 👍

**Pull request closed without merging**
