### PR TITLE
Moved js templates to a separate framework

### PR DESCRIPTION
**Pull request by ilyapuchka**
Moved ejs templates to a separate framework as discussed in #501 and slightly changed its API to make it more generic. Have no idea how to set it up for CocoaPods so that SourceryJS can be used as a separate dependency. Probably requires creating another spec for it, but it will depend on SourceryRuntime which should be then extracted too, but then we will need to publish all of them separately. Unfortunately subspec seems to be not suitable for such setup. Advices will be appreciated.

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
you can have a single podspec with multiple specifications and single update mechanism, take a look at this: https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec

**Comment by ilyapuchka** [comment]
I was trying to do that with subspecs, but if I understand correctly they still produce a single framework target with a name defined in the parent spec. When I wanted to describe several targets which depend on SourceryRuntime framework for each framework and also a tool itself, which has only binary source, not just a single target with subset of functionality. 
When I tried to do that and was linting SourceryJS subspec I saw that in the dummy project it was creating `Sourcery` framework built of SourceryRuntime sources, but I'm importing SourceryRuntime, so it fails to build.

**Comment by krzysztofzablocki** [comment]
ah well, I guess we'll need to update create separate spec for the each framework then ¯\_(ツ)_/¯

Btw the code looks fine, I've not used ejs, but as long as tests will pass this is fine to merge

**Comment by ilyapuchka** [comment]
I think I'll need #478 to fix SPM (can't find a way to define a dependency for additional target), so I'll merge it first and them will rebase this

**Comment by ilyapuchka** [comment]
Should work now. 
@krzysztofzablocki I would merge it then and continue extraction of other parts. I think we can figure out what to do with CocoaPods later. I don't like much the idea of having two separate specs. We probably can try to use subspecs to allow users to choose what functionality they need, but provide everything under one framework target (similar to SourceKitten). We will need some alternations in imports in that case though (i.e. do not import SourceryRuntime in SourceryJS sources when we build them into one target)

**Pull request merged**
