### PR TITLE
Scanning multiple targets

### PR DESCRIPTION
**Pull request by ilyapuchka**

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
this is pretty rad, any idea why the SPM error happens ? I'm traveling but I'll try to play with this over the weekend and get you a review

**Comment by ilyapuchka** [comment]
@krzysztofzablocki looks like SPM does not work well with submodules. I think also fixed ci build issues with CommonCrypto 🎉  but looks like there is a flaky test for watcher

**Comment by krzysztofzablocki** [comment]
any chance we could get rid of submodule? it feels like we are complicating it, we already use cocoapods for dependency management

**Comment by ilyapuchka** [comment]
Sure, we can. I'd like to use it with CocoaPods too, but this framework does not support it and I don't think that publishing spec for the fork is a good idea.

**Comment by krzysztofzablocki** [comment]
are they against adding spec to their repo ?

**Comment by ilyapuchka** [comment]
I just created a PR for that https://github.com/tomlokhorst/Xcode.swift/pull/19

**Comment by tomlokhorst** [comment]
Hi, I'm the developer of [Xcode.swift](https://github.com/tomlokhorst/Xcode.swift) and I noticed this issue due the PR.

Based on @ilyapuchka's work, I've added a podspec to the project (as well as Carthage and SPM support).

I intended to rename my project to XcKit, but I ran into a name conflict on CocoaPods. So as of yet I haven't released it to CocoaPods, until I can come up with a good name that isn't already taken. I'm sure Sourcery can appreciate the difficulty of [naming a project](https://github.com/krzysztofzablocki/Sourcery/issues/2). ;-) 

While I haven't used Sourcery yet, I'm a big fan of code generation in general, so I appreciate this project! If you have feature requests for Xcode.swift to support Sourcery, feel free to open an issue or send a pull request. I'd be happy to help.

**Comment by ilyapuchka** [comment]
Thanks @tomlokhorst ! I actually kind of liked Xcode.swift name =)

**Comment by tomlokhorst** [comment]
For the dependency: I've renamed Xcode.swift to XcodeEdit, and released the CocoaPod.

You can now depend on:
`pod 'XcodeEdit', '~> 1.0'`
or:
`.Package(url: "https://github.com/tomlokhorst/XcodeEdit.git", majorVersion: 1)`

**Comment by ilyapuchka** [comment]
@tomlokhorst can you please also rename the project and the Package name to XcodeEdit? Otherwise it creates XcKit module when building with SPM and XcodeEdit for CocoaPods.

**Comment by tomlokhorst** [comment]
@ilyapuchka Update the SPM dependency for XcodeEdit to version 1.0.0, instead of 0.4.0.

**Pull request merged**
