### PR TITLE
Made AutoCases uses let constants instead of computed vars

### PR DESCRIPTION
**Pull request by AliSoftware**
This feels more swifty and efficient (computed only once)

BTW, not sure if:

* there are any tests for templates provided in the repo (I didn't found any, and tests are passing locally)
* there's something to regenerate in the documentation in case the doc quotes this template somewhere (and if so, how to)

### CODE REVIEW

**Comment by ilyapuchka** [comment]
Hey @AliSoftware !
To update the docs just run `jazzy --clean` (will add this to the pr template)
I guess the only thing to update in docs is `guides/Enum cases.md` where it has example output

**Comment by AliSoftware** [comment]
Thx. It has been some time since I've installed jazzy, have a way outdated version that doesn't work anymore. Will probably not have much time to reinstall it properly to regen docs before NSBudapest/CraftConf, so feel free to run it and push there, would probably be faster (otherwise I'll try not to forget to do it after the conferences)

**Comment by AliSoftware** [comment]
Also, do you expect a CHANGELOG entry for changes in the template examples?

**Comment by ilyapuchka** [comment]
Yep, just put it under "Internal changes" maybe

**Comment by ilyapuchka** [comment]
"there are any tests for templates provided in the repo (I didn't found any, and tests are passing locally)" - that's a good point actually. If we want to present these templates as ready for use, not just as an example and starting point for writing something on your own, we definitely need to test it. 
But maybe it will make more sense to separate it in a submodule (maybe using sub spec or something) and write more integration tests there based on these templates. It also popped up several times lately that people try to use Sourcery with these templates though they don't even need them. We discussed that back in #10, maybe we need to reopen it.

**Comment by AliSoftware** [comment]
@ilyapuchka you could get some inspiration from our SwiftGen/templates repo that contains both templates and fixtures. We now tests those templates on CircleCI to ensure the code generated by those templates compile properly. Would be nice to do the same for Sourcery.

**Pull request merged**
