### PR TITLE
Add lowerFirst function in stencil.

### PR DESCRIPTION
**Pull request by yageek**
Generating enum cases from type name would require the first letter to
be lowercase.

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
Thanks for contributing, we already have `lowerFirstWord` since we inherit filters from https://github.com/SwiftGen/StencilSwiftKit, but this works a little different, since its just first letter not whole word, so I'm ok merging it.

Could you add changelog entry to make Danger happy?

**Comment by yageek** [comment]
Sure. Should I regenerate jazzy documentation too?

**Comment by krzysztofzablocki** [comment]
@yageek yeah, good catch :) I should add it to danger when I fly back home

**Comment by AliSoftware** [comment]
Shouldn't we actually migrate that new filter into StencilSwiftKit instead? (I know I'm quite late on releases but there's normally a new one coming soon to catch up)

**Comment by krzysztofzablocki** [comment]
We'll need to look through all filters and move the generic ones to stencil swift kit

**Pull request merged**
