### PR TITLE
[WIP] Caching parsing artifacts

### PR DESCRIPTION
**Pull request by krzysztofzablocki**
This enables caching code artifacts.

Should we store cache in derived data? I think that would require users to pass that data in from their build phase

cc @bejar37 @kzaher @bolismauro take a look, I'd also appreciate some performance comparison if you can :)

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
btw. @ilyapuchka I had to flatten the classes because NSCoding didn't play well with nested types

**Comment by bolismauro** [comment]
@krzysztofzablocki about 83% faster with respect to master
How many files NY app has (I've read it takes less than 1 sec)

**Comment by krzysztofzablocki** [comment]
@bolismauro a bit over 300 files

**Comment by bejar37** [comment]
I'm seeing similar improvements to @bolismauro, 👍 !!

**Pull request merged**
