### PR TITLE
[WIP] migrate to CircleCI 2.0

### PR DESCRIPTION
**Pull request by ZevEisenberg**
Should preserve the build steps correctly, but it doesn’t exactly translate 1:1 from the old configuration. Maybe there’s a better way to structure things? Maybe it can be paralelizwd?

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
@ilyapuchka @krzysztofzablocki question about the Circle config file. It currently has this in it:

```sh
ln -s /Applications/Xcode-8.3.app /Applications/Xcode.app
```

Is this something you still want to be doing? Or is it a relic of a bygone era?

**Comment by ZevEisenberg** [comment]
I just found out about the 1.0 to 2.0 config migrator. It might be useful to have someone with admin access to this project in CircleCI to hit this endpoint and see what it returns: https://circleci.com/docs/2.0/migrating-from-1-2/

**Comment by ZevEisenberg** [comment]
Latest build failed because of something something Ruby. Anyone know why? https://circleci.com/gh/krzysztofzablocki/Sourcery/1300

As a workaround, I think I can update jazzy, but let me know if that's too large a change.

**Comment by ZevEisenberg** [comment]
That didn't work. Going to try this next. https://github.com/bundler/bundler/issues/3372

**Comment by djbe** [comment]
I also had ruby version issues in our SwiftGen migration, see https://github.com/SwiftGen/SwiftGen/pull/403.

For SwiftGen, we use the Xcode 9 image, which has ruby 2.4.2. For StencilSwiftKit, we still use a Xcode 8.3 image, which has ruby 2.4.1 (see https://github.com/SwiftGen/StencilSwiftKit/pull/81/commits/dc348bb4b13055f6dd0c614c4340674d9c5f86f7).

**Comment by ilyapuchka** [comment]
@ZevEisenberg @djbe thanks! I solved bundle install problem, I'll take it from here

**Pull request merged**
