### PR TITLE
[#1251] Swifty generated variable names + fixed generated mocks compi…

### PR DESCRIPTION
**Pull request by rokridi**
…lation issues due to method generic parameters

### CODE REVIEW

**Review by krzysztofzablocki — APPROVED** [review]

**Comment by art-divin** [comment]
Hello @rokridi, 

thank you for your contribution. 

Unfortunately, I did not foresee the issue with generic parameters, indeed, with the latest changes related to support of method override in mockable methods.

Your PR has not updated the existing expected generated mock results, thus CI fails. 
If you can, would be amazing for you to regenerate the whole expected suite located under `/Templates/Tests/Expected/AutoMockable.expected` 👏🏻  

But if it is too much for you - totally fine, just please express that so we won't do double work 🤝

**Comment by rokridi** [comment]
Hi @art-divin 👋 

It would be great if you regenerated the expected suite.

Thank you very much.

**Comment by art-divin** [comment]
Thank you @rokridi , done in #1253 🤝

**Comment by rokridi** [comment]
Thank you 🥳 🍉

**Pull request merged**
