### PR TITLE
Add support for free functions

### PR DESCRIPTION
**Pull request by maxmamis**
As mentioned in https://github.com/krzysztofzablocki/Sourcery/issues/806, I have a use-case that requires working with free functions. I decided to see what would be involved in making this work and it turns out it's not too bad. 

This is a naive implementation meant as an aid for discussion, it's not production-ready yet. Notably I didn't add tests yet, or test support for templating languages other than Stencil.

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
@maxmamis this looks great and honestly that's where I'd put those functions, as top level object and sibling of `types`, is there anything missing here functionality-wise, other than proper tests ?

**Comment by maxmamis** [comment]
I believe this is complete, though I haven't tested it with JS templates yet. I also was seeing an issue where I didn't have full metadata for return types, but I'm not sure whether that's a separate issue

**Comment by maxmamis** [comment]
thanks for the feedback! I'll add/fix the tests as soon as I get a chance

**Comment by krzysztofzablocki** [comment]
@maxmamis if metadata is missing that would suggest to me you need to modify the unifying phase in `Composer.swift`, shouldn't be complicated as we already do this for normal types

**Comment by maxmamis** [comment]
Thanks, I'll take a look there

**Comment by maxmamis** [comment]
@krzysztofzablocki Updated `Composer.swift` to fix the issue I was seeing and added a few tests for free functions — wasn't sure how far down the rabbit hole I should go (should I test that it parses every kind of parameter and return type properly?), please let me know if you'd like to see some more. Otherwise ready for a full review!

**Comment by krzysztofzablocki** [comment]
@maxmamis this looks good, maybe you could write a very simple template for EJS / Swift and add a test to each to prove that functions are processed correctly in those scenarios? the template could simply read the free function and generate another one from it

**Comment by maxmamis** [comment]
@krzysztofzablocki Added!

**Comment by krzysztofzablocki** [comment]
great job, thanks for contributing 👏

**Pull request merged**
