### PR TITLE
Upgrade 3rd party dependencies to support project contains swift package

### PR DESCRIPTION
**Pull request by junjielu**
fix the [issue](https://github.com/krzysztofzablocki/Sourcery/issues/816)

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
thanks for contributing @junjielu but you still have references to old `xcproj`, can you update it? Command line command `rake tests` needs to pass

**Comment by junjielu** [comment]
> thanks for contributing @junjielu but you still have references to old `xcproj`, can you update it? Command line command `rake tests` needs to pass

Yes, I can.I will find some time to fix this issue

**Comment by VasylKo** [comment]
Hi. Any update here?

**Comment by RomanTysiachnik** [comment]
@VasylKo There're few tests failing with a new XcodeProj version. Couldn't detect an issue yet. Feel free to join :)

**Comment by vCrespoP** [comment]
+1 

I can confirm we're having this

**Comment by krzysztofzablocki** [comment]
move over to #896 where I updated everything

**Pull request closed without merging**
